name = "test-agents"
main = "src/director.js"
compatibility_date = "2024-01-01"
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[ai]
binding = "AI"

[[d1_databases]]
binding = "HOPE_TREE" # This is how the Worker accesses the database
database_name = "hope-tree"
database_id = "4a03855b-1813-448f-9aca-7bae4f4a4033"